server:
  port: 8080
  timeout: 30s

redis:
  urls:
    - "redis://redis-1:6379"
    - "redis://redis-2:6379"
    - "redis://redis-3:6379"
  pool_size: 20
  timeout: 5s
  max_retries: 3

logging:
  level: info
  format: json
